image : mcr.microsoft.com/dotnet/sdk:7.0

stages:
  - test-run

test-run:
  stage: test-run
  script:
    - dotnet run --project ./BoolIsUpperChar/BoolIsUpperChar.csproj Y
  artifacts:
    paths:
      - test/*.jar
